### PR TITLE
Fix #if Conditional Logix

### LINKED ISSUE #31: #if(variable) fails check if variable exists in context
Quoting Leaf documentation about `#if`:

> if you provide a variable it will check that variable exists in its context

The latest Leaf engine doesn't follow this convention: it only evaluates Bool `true` as true, all other values including `nil` and strings evaluated as `false`.

In other words, no matter what you provide it'll always be treated as `false` unless Bool `true` provided.

Small experiment:

```html
<p>Title = #(title)<br>
#if(title):
    The 'title' is #(title)
#else:
    No 'title' was provided.
#endif
</p>

<p>Nonexistent = #(nonexistent)<br>
#if(nonexistent):
    The 'nonexistent' is #(nonexistent)
#else:
    No 'nonexistent' was provided.
#endif
</p>
```

Results in:

```
Title = Home
No 'title' was provided.

Nonexistent =
No 'nonexistent' was provided.
```

### PR DESCRIPTION
**Pull request by b-straub**
Fixes `#if` to support checking a value's truthiness like Leaf 3 did (#28, fixes #31). 
- Fix null handling for conditionals
- Fix boolean reduction for future parameter lists with > 1 boolean values
- Restored and updated leaf3 "testStringIf" test
- Added tests for conditional and/or

### CODE REVIEW

File: Sources/LeafKit/ParameterResolver.swift [hunk 1]
```diff
@@ -115,7 +115,7 @@ struct ParameterResolver {
     private func resolve(op: Operator, rhs: LeafData) throws -> LeafData {
         switch op {
         case .not:
-            let result = rhs.bool ?? false
+            let result = rhs.bool ?? !rhs.isNull
```
Comment (tanner0101) [inline Sources/LeafKit/ParameterResolver.swift]: Would this make sense as an extension on `LeafData` so we don't need to repeat it?

```swift
extension LeafData {
    var isTruthy: Bool {
        self.bool ?? !self.isNull
    }
}
```

Comment (tanner0101) [reply Sources/LeafKit/ParameterResolver.swift]: We might also consider supporting `1` or `"true"` as truthy.

**Comment by tanner0101** [comment]
I'm going to merge this through with the notes for possible improvement outstanding since it's blocking people. Thanks @b-straub!

**Comment by tanner0101** [comment]
These changes are now available in [1.0.0-rc.1.1](https://github.com/vapor/leaf-kit/releases/tag/1.0.0-rc.1.1)
